server:
  port: 8088
  connection-timeout: 1000ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  #测试主库
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
          master:
             url: jdbc:mysql://45.32.254.172:3306/tcc_order?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
             username: admin
             password: admin
             validation-query: SELECT 1
             initial-size: 5
             max-active: 100
             min-idle: 5
             max-wait: 6000
             remove-abandoned: true
             remove-abandoned-timeout-millis: 1800
             time-between-eviction-runs-millis: 60000
             min-evictable-idle-time-millis: 25200000
             filters: wall
             stat-view-servlet:
                   enabled: false
             use-global-data-source-stat: true
          slave:
             url: jdbc:mysql://45.32.254.172:3306/tcc_account?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
             username: admin
             password: admin
             validation-query: SELECT 1
             initial-size: 5
             max-active: 100
             min-idle: 5
             max-wait: 6000
             remove-abandoned: true
             remove-abandoned-timeout-millis: 1800
             time-between-eviction-runs-millis: 60000
             min-evictable-idle-time-millis: 25200000
             filters: wall
             stat-view-servlet:
                   enabled: false
             use-global-data-source-stat: true
 # Redis数据库索引（默认为0）
  redis:
      database: 0
      host: 45.32.254.172
      port: 6379
      password:
      timeout: 3600ms
      jedis:
        pool:
          max-active: 50
          max-wait: 1000ms
          max-idle: 8
          min-idle: 0
logging:
  config:
          classpath: log4j2.xml
